CREATE TABLE authors (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE books (
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR NOT NULL UNIQUE,
	author_id BIGINT NOT NULL,
	FOREIGN KEY(author_id) REFERENCES authors(id),
	description VARCHAR NOT NULL,
	quantity INTEGER NOT NULL,
	cover VARCHAR,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	username VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	pass VARCHAR NOT NULL, -- bcrypt hashed password
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);

CREATE TABLE borrowing_records (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id),
	book_id BIGINT NOT NULL,
	FOREIGN KEY(book_id) REFERENCES books(id),
	status VARCHAR NOT NULL,
	borrowing_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	returning_date TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);
